# Generated by Django 3.2.7 on 2021-09-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_repos'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='user_name',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
        migrations.RemoveField(
            model_name='repository',
            name='name',
        ),
        migrations.AddField(
            model_name='repository',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
    ]
